Update TS code for initializing mapping storage
RareSkills/solana-tutorial pull request #7
Opened 2024-08-31 07:49 UTC by jereldlimjy

- Corrected the initialization of the `seeds` array
- Update `valueAccount` to be the first element of the returned array
- Removed trailing commas after `program.programId`

2024-09-12 19:18 UTC, tanim0la commented
ok to merge 👍

2024-09-13 15:37 UTC, jeffreyscholz requested changes

2024-09-13 15:37 UTC, jeffreyscholz commented on content/solana-solidity-mapping/en/solana-solidity-mapping.md
> +    const seeds = [key.toArrayLike(Buffer, "le", 8)];
Can we undo this change? imo "seeds" is not accurate because it also includes the bump, then we get rid of it by adding [0] at the end.

2024-09-13 16:09 UTC, tanim0la commented on content/solana-solidity-mapping/en/solana-solidity-mapping.md
> +    const seeds = [key.toArrayLike(Buffer, "le", 8)];
`findProgramAddressSync` method takes in 2 args; `array of bytes` and `programId`

The `seeds` constant here stores the conversion of `key` to 8 bytes buffer

2024-09-14 03:41 UTC, jeffreyscholz commented on content/solana-solidity-mapping/en/solana-solidity-mapping.md
> +    const seeds = [key.toArrayLike(Buffer, "le", 8)];
ok fair, will merge

2024-09-14 03:41 UTC, jeffreyscholz approved these changes

2024-09-14 03:41 UTC, merged